### ISSUE TITLE
createForZoneName no longer working for "Europe/Amsterdam"

### ISSUE THREAD

**Issue by rvdbreemen** [bxparks/AceTime#106]
With the current AceTime release the .createForZoneName is no longer working for my default timezone, which is the Netherlands?

It had been a while since I updated your library to the latest and the greatest. And I use it to lookup user input to match with a TimeZone name. Now the default always works, which is "Europe/Amsterdam". 

I have taken your Hello Timezone Manager example, and extended it with some entries:

``` // Create Europe/London timezone by ZoneName.
  TimeZone londonTz = manager.createForZoneName("Europe/London");
  ZonedDateTime londonTime = losAngelesTime.convertToTimeZone(londonTz);
  londonTime.printTo(SERIAL_PORT_MONITOR);
  SERIAL_PORT_MONITOR.println();

  // Create Europe/Amsterdam timezone by ZoneName.
  TimeZone amsterdamTz = manager.createForZoneName("Europe/Amsterdam");
  ZonedDateTime amsterdamTime = losAngelesTime.convertToTimeZone(amsterdamTz);
  amsterdamTime.printTo(SERIAL_PORT_MONITOR);
  SERIAL_PORT_MONITOR.println();
  
  // Create Europe/Brussels timezone by ZoneName.
  TimeZone brusselsTZ = manager.createForZoneName("Europe/Brussels");
  ZonedDateTime brusselsTime= losAngelesTime.convertToTimeZone(brusselsTZ);
  brusselsTime.printTo(SERIAL_PORT_MONITOR);
  SERIAL_PORT_MONITOR.println();

Output:
2019-03-10T03:00:00-07:00[America/Los_Angeles]
2019-03-10T10:00:00+00:00[Europe/London]
<Invalid ZonedDateTime>
2019-03-10T11:00:00+01:00[Europe/Brussels]
2019-03-10T21:00:00+11:00[Australia/Sydney]

**Comment by rvdbreemen** [comment]
I have been playing around, but it seems that more entries can't be looked up anymore, like:

Europe/Oslo
Europe/Stockholm
etc.

**Comment by bxparks** [comment]
Try changing the initialization of the `ExtendedZoneManager` from
```C++
static ExtendedZoneManager manager(
    zonedbx::kZoneRegistrySize,
    zonedbx::kZoneRegistry,
    zoneProcessorCache);
```
to
```C++
static ExtendedZoneManager manager(
    zonedbx::kZoneAndLinkRegistrySize,
    zonedbx::kZoneAndLinkRegistry,
    zoneProcessorCache);
```

The IANA TZ database continues to merge zones and convert previously Zone entries into Link entries. The `zonedbx::kZoneRegistry` registry contains only Zone entries.

If this solution works, we should update that example to use the `kZoneAndLinkRegistry`. But adding the Link entries does increase the size of the database, from about 40kB to 49kB for an ESP8266 according to https://github.com/bxparks/AceTime/tree/develop/examples/MemoryBenchmark#esp8266.

If this doesn't work, I'll have to dig deeper.

**Comment by rvdbreemen** [comment]
Hi Brian,
Yes, this works. Then the example needs to be updated then.  The size growth should not be an issue I think in my situation on the ESP. 

Thanks for your amazing support and wonderful work on this library,
Keep up the great work,
Robert

**Comment by bxparks** [comment]
Glad that fixes it for you
