### ISSUE TITLE
gcc 11.3 compiler warning

### ISSUE THREAD

**Issue by skunktrading** [bxparks/AceTime#107]
I recently upgraded the toolchain I am using to build from gcc 5.4.1 to 11.3.1.

The compiler now emits this warning that looks valid although probably innocuous seeing that the code explicitly null terminates the string immediately after the strncpy call
`In static member function 'static void ace_time::ExtendedZoneProcessorTemplate<BF, ZIB, ZEB, ZPB, ZRB>::createAbbreviation(char*, uint8_t, const char*, uint16_t, const char*) [with BF = ace_time::extended::BrokerFactory; ZIB = ace_time::extended::ZoneInfoBroker; ZEB = ace_time::extended::ZoneEraBroker; ZPB = ace_time::extended::ZonePolicyBroker; ZRB = ace_time::extended::ZoneRuleBroker]',
    inlined from 'static void ace_time::ExtendedZoneProcessorTemplate<BF, ZIB, ZEB, ZPB, ZRB>::createAbbreviation(char*, uint8_t, const char*, uint16_t, const char*) [with BF = ace_time::extended::BrokerFactory; ZIB = ace_time::extended::ZoneInfoBroker; ZEB = ace_time::extended::ZoneEraBroker; ZPB = ace_time::extended::ZonePolicyBroker; ZRB = ace_time::extended::ZoneRuleBroker]' at .pio/libdeps/teensy41/AceTime/src/ace_time/ExtendedZoneProcessor.h:2115:17,
    inlined from 'static void ace_time::ExtendedZoneProcessorTemplate<BF, ZIB, ZEB, ZPB, ZRB>::calcAbbreviations(ace_time::ExtendedZoneProcessorTemplate<BF, ZIB, ZEB, ZPB, ZRB>::Transition**, ace_time::ExtendedZoneProcessorTemplate<BF, ZIB, ZEB, ZPB, ZRB>::Transition**) [with BF = ace_time::extended::BrokerFactory; ZIB = ace_time::extended::ZoneInfoBroker; ZEB = ace_time::extended::ZoneEraBroker; ZPB = ace_time::extended::ZonePolicyBroker; ZRB = ace_time::extended::ZoneRuleBroker]' at .pio/libdeps/teensy41/AceTime/src/ace_time/ExtendedZoneProcessor.h:2098:27:
.pio/libdeps/teensy41/AceTime/src/ace_time/ExtendedZoneProcessor.h:2149:18: warning: 'char* strncpy(char*, const char*, size_t)' specified bound 7 equals destination size [-Wstringop-truncation]
 2149 |           strncpy(dest, format, destSize);
      |           ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
`
Perhaps the final argument should be changed to destSize-1 like line #2126?

**Comment by bxparks** [comment]
What compiler flags are you using? I use g++ 11.3.0 on Ubuntu 22.04 and don't get this warning with `-Wextra -Wall`, or even with`-pendatic`. I don't get this warning even on clang++ 14.0.0 which is often more strict.

Can you copy and paste a few lines above and below the error? I just finished some extensive refactoring and I don't know what code line 2149 or 2126 points to.

**Comment by skunktrading** [comment]
Sure
`2125        if (letterString == nullptr) {
2126          strncpy(dest, format, destSize - 1);
2127          dest[destSize - 1] = '\0';
2128        } else {
`

`2147        } else {
2148          // Just copy the FORMAT disregarding deltaMinutes and letterString.
2149          strncpy(dest, format, destSize);
2150          dest[destSize - 1] = '\0';
2151        }
`

**Comment by skunktrading** [comment]
Thanks. It looks like you already committed the fix :)

**Comment by bxparks** [comment]
Yup, I figured out what you were referring to and changed it. I don't know how to verify this, but I'm going to close it, with the assumption that you can re-open it.
