### ISSUE TITLE
Add support for other HW RTCs

### ISSUE THREAD

**Issue by Naguissa** [bxparks/AceTime#21]
Hello,

I've seen your project has DS3231 support.

I want to suggest to add DS3232 support. It uses same control registers so you can use same files or simply add a note about supporting this RTC.

Also you can add DS1307 support; works the same as DS3232 but you may need to change addresses a little.

I've developed a minimal RTC library where you can see how they work, and there I have the three RTCs datasheets: https://github.com/Naguissa/uRTCLib/tree/master/extras

Cheers!

**Comment by Naguissa** [comment]
Hello again,

I don't have none of them, but if you check datasheets DS3232 have just same control registers as DS3231, the only change is that it adds some SRAM after all control registers (same kind of SRAM as old DS1307 has).

Cheers!

**Comment by Naguissa** [comment]
Perfect!

Let's hope anyone can test it, it'squite simple but you need the real hardware.

But one note, the identical one is DS3232, the other one changes a little.


Cheers!

**Comment by Naguissa** [comment]
Other thing: I'll try to add the code and make a PR, but I cannot test it.

**Comment by Naguissa** [comment]
Can'tyou make a branch and ask any uset to test it?

**Comment by Naguissa** [comment]
I'll do! even adding a compiler message.

PS: I'm CTO in a company, Arduino and electronics is also my hobby.

**Comment by Naguissa** [comment]
Checked. No code change is needed, only adding compatibility info.

**Comment by Naguissa** [comment]
(Oh! And I've made a PR. Consider changing the texts to fit your wishes)

**Comment by bxparks** [comment]
Merged 834fe7a. I think we can close this?
