### ISSUE TITLE
Construct NtpClock assuming network is available

### ISSUE THREAD

**Issue by denis-stepanov** [bxparks/AceTime#24]
I have difficulty understanding the choice to constuct NtpClock with Wi-Fi parameters. In a project which already uses Wi-Fi for other reason (e.g., running a web server), is there a way to create an NTP clock without running a Wi-Fi setup?

Thanks.

**Comment by bxparks** [comment]
That's a good point. It's because I haven't needed to use the WiFi for anything except for NTP time so far. Do you have some suggestions? Maybe another constructor that does not require the `setup()` method to be called? I'm happy to look at well-crafted pull requests.

**Comment by denis-stepanov** [comment]
Thanks. I am thinking about constructor with no parameters; other operations should check that Wi-Fi is connected before interacting with the network. With setup() or not, it's worth doing this anyway, because Wi-Fi connection can go away any time. Perhaps, a constructor could take an optional WiFiUDP object, for projects which have already allocated it for their own use.

I'll try to submit something along these lines, but no hard promise :-)

**Comment by bxparks** [comment]
I made some tweaks and fixes, and pushed them to the develop branch. Things look good.

I'll leave this issue open for now, until I get back from vacation. (Will be unable to respond for a couple of weeks.)

**Comment by denis-stepanov** [comment]
Thanks.
