### ISSUE TITLE
Day of week calculation is off by one

### ISSUE THREAD

**Issue by aureliorramos** [bxparks/AceTime#28]
Your day of the week calculation is off by one. Today, Saturday, it returns 1. Oh and this is a leap year....not sure if this matters

**Comment by bxparks** [comment]
Today, 2020-02-08, Saturday, I get `LocalDate::kSaturday`, which is 6, which is correct.
Can you post a minimal reproducible code, and identify what microcontroller you are using? What is the the "**it**" that you are referring to? Please give me some information that let's me debug something...

**Comment by aureliorramos** [comment]
I believe I understand the cause of my issue. it was user error:

Neglected that AceTime does not use unix epoch as noted in the intro page.
you may close the issue.
