### ISSUE TITLE
In OLED clock manual mode, can't set the clock

### ISSUE THREAD

**Issue by dduehren** [bxparks/AceTime#31]
I fixed this in controller.h by adding a manual config in setup.  The code is below.  I'm not an expert on git and don't have the time right now to do a pull request.   Once some time is set, the manual clock change buttons, etc will work.  But without this, it stays stuck at "Error".   The new code is below      setupClockInfo();

    void setup() {
      // Restore from EEPROM to retrieve time zone.
      StoredInfo storedInfo;
      bool isValid = mPersistentStore.readStoredInfo(storedInfo);
    #if FORCE_INITIALIZE
      setupClockInfo();
    #else
      if (isValid) {
        restoreClockInfo(mClockInfo, storedInfo);
      } else {
        setupClockInfo();
        auto pacificTz = mZoneManager.createForZoneIndex(mZoneIndex);
        // Set the SystemClock using these components.
        auto pacificTime = ZonedDateTime::forComponents(
        2020, 2, 5, 4, 30, 0, pacificTz);
        mClock.setNow(pacificTime.toEpochSeconds());
      }
    #endif

      // Retrieve current time from Clock and set the current clockInfo.
      updateDateTime();
    }

**Comment by bxparks** [comment]
I am not able to reproduce any problems with the manual mode. What type of board are you using?

To be precise, I assume that you are setting the following in `config.h`?
```
#define TIME_ZONE_TYPE TIME_ZONE_TYPE_MANUAL
```

With this defined, the `Controller::setup()` method should call `Controller::setupClockInfo()`, which, in the manual mode, should set the timeZone to be UTC-08:00, and then everything should work after that.

If you happened to switch between the various modes (e.g. `TIME_ZONE_TYPE_BASIC` first, then to `TIME_ZONE_TYPE_MANUAL`,)it is possible the code does not fully configure the state of the clock properly. This is not a code path that I have extensively debugged.

The escape hatch is `FORCE_INITIALIZE`. If you set that to 1, then the various internal variables should reset to their "factory" defaults. Then you would set that to 0, and recompile the program and upload to the board. Then everything should work normally after that.

**Comment by dduehren** [comment]
Hi Brian,

 

I may have mischaracterized it.  I didn’t test it in full manual mode. It as NTP mode with no wifi connection.  And I did make it work, so it’s fine if it’s closed.

 

*	David

**Comment by bxparks** [comment]
Ok. In any case, you motivated me to add more details into the README.md for this example program.
